### ISSUE TITLE
Hello and BBG (Green)/Seeed-Studio and the Wiki

### ISSUE THREAD

**Issue by silver2row** [Seeed-Studio/Grove_Starter_Kit_for_BBG#1]
Hello,

I am having trouble with some of the software for the BBG Wiki with AWS and Cloud9. This is what pops up: module.js:340
    throw err;
          ^
Error: Cannot find module '../src/aws_iot.js'

I cannot find this file/module because I think the name has changed. I have not found this file/module to be in my files or directories. I looked through most of what was easily seen.

I am also getting negative feedback/syntax errors for time_pub.js and time_sub.js, respectively. The software is not running with success.

I can try to figure it out but it would take time. My software for Python-App.py runs until it shows a syntax error on: File "Python-App.py", line 5
    client.connect((127.0.0.1', 7000))
                          ^
SyntaxError: invalid syntax

P.S. I have found many syntax errors in the software I downloaded from Seeed-Studio's Github.com account. Please send guidance. I will work with you.

**Comment by silver2row** [comment]
Hello Again,

One more thing. The file, IotSdkJS, does not exist any longer. I could not find this file. There is another file I could not find, ../src/aws_iot.js. I think the names have changed for these files and for the software.

Sincerely,

Seth

**Comment by Pillar1989** [comment]
https://github.com/Seeed-Studio/AWS_SDK_for_BBG/blob/master/src/aws_iot.js

**Comment by Pillar1989** [comment]
Hi all,
     AWS firmware was updated, the Newest : https://drive.google.com/file/d/0BwBIy7Eq4Nucd3NTaUkzS0dtT2s/view?usp=sharing ,Please updated.

**Comment by silver2row** [comment]
Hello,

I am bugging you again. Sorry but here goes it...the "aws_iot.js" file with all that awesome software is not in my directories or libraries when I clone the Starter_Kit_for_BBG. The clone works but when I clone the library, the aws_iot.js file is missing. 

I tried to clone the .js file to my cloud9 IDE but I failed. Is it possible to clone the .js file without using that image/firmware? I do not want to write a new image from AWS.

Sincerely,

Seth

**Comment by silver2row** [comment]
Hello Again,

Oh and there is no prodCerts folder. Should I already have this file in my library once it has been cloned?

Sincerely,

Seth

**Comment by silver2row** [comment]
Hello...I am so sorry to keep bothering you. This site on github.com does not register with 192.168.7.2:3000 (the cloud9 IDE): https://github.com/aws/aws-iot-device-sdk-js/blob/master/README.md#overview. 

Please see that page because it does not work. I just tried it. I cloned the info. into my IDE and placed credentials and password to get the .js file. Nothing worked. Heads up!

Sincerely,

Seth

**Comment by silver2row** [comment]
Hey Man...I figured it out. You have to use npm instead of cloning it from Github.com.

Sincerely,

Seth

**Comment by silver2row** [comment]
So, it is:
1. npm install aws-iot-device-sdk

Even on the AWS github.com page, they show how to clone it. That clone is invalid for some reason.

Sincerely,

Seth

**Comment by silver2row** [comment]
One last thing. Hello again...the HelloWorld.js file is no longer available in the aws-iot-device-sdk from AWS (I think). Are you the person that offers this HelloWorld.js file? If so, how can I get it?

Sincerely,

Seth

**Comment by Pillar1989** [comment]
https://github.com/Seeed-Studio/AWS_SDK_for_BBG/blob/master/example/Helloworld.js

**Comment by silver2row** [comment]
Pillar,

 

Hello…let me clone it. Please. I tried to clone it and it would not work. 

 

Sincerely,

 

Seth Nowlin

Silver1row@cox.net <mailto:Silver1row@cox.net> 

 

P.S. Again man, thank you for your support. You are a life saver. I mean it.

**Comment by Jack1314** [comment]
Hi，silver2row：

Please try to clone the whole folder
https://github.com/Seeed-Studio/AWS_SDK_for_BBG

**Comment by silver2row** [comment]
Hello Pillar,

Okay. I will try. Thank you once more. 

Sincerely,

Seth

**Comment by silver2row** [comment]
Hello Jack,

Thank you sir. I cloned it. It worked. Thank you and thank Pillar for me. I appreciate the assistance. I make mistakes sometimes. 

Sincerely,

Seth
