### ISSUE TITLE
RE: The Oled Example...

### ISSUE THREAD

**Issue by silver2row** [Seeed-Studio/Grove_Starter_Kit_for_BBG#2]
Hello,

I am using smbus2 via a pip3 install to handle the i2c mechanics of it all. The library that was used for i2c from Adafruit is deprecated.

I am trying to make the Oled example work but I am getting some issues upfront. 

...

Do these libraries/examples work still? Do they work w/ the BBGW?

Seth

**Comment by baorepo** [comment]
https://github.com/rm-hull/luma.oled @silver2row  OLED recommends the use of this software.
